### PR TITLE
Reinstate fmu.ensemble.etc for API compatibility

### LINKED ISSUE #192: submodule etc is missing
Pull request #184 incurred an API change, and usage of the `etc` submodule is present in user scripts (it was in the documentation).

Reinstate the module in order to give a DeprecationWarning is a possibility, the code

```
fmux = ensemble.etc.Interaction()   
logger = fmux.basiclogger(__name__, level='WARNING')
```
should not crash.

### PR DESCRIPTION
**Pull request by berland**
Resolves #192

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by markusdregi** [comment]
@berland: Any reason you are not introducing all of the `etc` module?

Besides that, the deprecation and testing of it is good 👏

**Comment by berland** [comment]
It is unlikely that there are user-scripts with anything else than what was in the documention, that is why I chose to only ensure that did not crash. I choose to not replicate exact logging behavior, rather trigger people to maintain their code.

**Comment by markusdregi** [comment]
Aight, if that was the only documented method I'm willing to accept that that was the only public part of the API... But, deprecated methods typically still function as expected. Are you sure you do not want to either introduce the old implementation of the function, or raise an exception instead of the deprecation warning?

**Comment by berland** [comment]
Aight, fully reinstated original code from v1.4.0, but with depr waraning. I envisioned it would trip other code, but it did not.

**Review by markusdregi — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
