### PR TITLE
Issue 228 fixed: The example for Representative realizations did not …

### PR DESCRIPTION
**Pull request by bkhegstad**
…work. Updated example will. In addition added numeric_only in .sum() because of warning

### CODE REVIEW

**Comment by bkhegstad** [comment]
Yes,  Indeed. It does not work without it. I missed out that one. Thanks

**Review by asnyv — APPROVED** [review]
LGTM 😊
Nice if you squash the commits when merging

**Comment by bkhegstad** [comment]
Hmm. There should be a Merge-button somewhere? Cannot see any? Do I not have the right permissions? Or am I looking at the wrong place? I assume that the squash is an option in the Merge-menu/workflow? 
Or should I do some git-magic from terminal?

**Comment by asnyv** [comment]
Ah ok, maybe you don't have write access. I'll merge then :)

**Pull request merged**
